# Generated by Django 5.0.1 on 2024-02-16 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_contactus_alter_blog_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
    ]
