# Generated by Django 5.0.1 on 2024-03-02 09:49

from django.db import migrations, models

def migrate_blog(apps,schema_editors):
    Blog = apps.get_model('core','Blog')
    for blog in Blog.objects.all():
        blog.title_en = blog.title
        blog.description_en = blog.description
        blog.slug_en = blog.slug
        blog.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_az',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_tr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='email_az',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='email_en',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='email_tr',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='message_az',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='message_en',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='message_tr',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='name_az',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='name_tr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='subject_az',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='subject_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='subject_tr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='address_az',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='address_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='address_tr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='email_az',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='email_en',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='email_tr',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='name_az',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='name_tr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_az',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_tr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='address_az',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='address_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='address_tr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='email_az',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='email_en',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='email_tr',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='name_az',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='name_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='name_tr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
