# Generated by Django 5.0.1 on 2024-03-05 11:16

from django.db import migrations, models
def migrate_blog(apps,schema_editors):
    Blog = apps.get_model('core','Blog')
    for blog in Blog.objects.all():
        blog.title_en = blog.title
        blog.description_en = blog.description
        blog.slug_en = blog.slug
        blog.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_category_name_az_category_name_en_category_name_tr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='description_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='slug_az',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='slug_tr',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_az',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_tr',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
