# Generated by Django 5.0.1 on 2024-03-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_blog_description_az_blog_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='slug_az',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='slug_en',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='slug_tr',
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('EL', 'Extra large'), ('XXL', 'Extra Extra large'), ('XXXL', 'Extra Extra Extra large')], default='M', max_length=50),
        ),
    ]
