# Generated by Django 5.0.1 on 2024-04-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_blog_slug_az_remove_blog_slug_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=' ', upload_to='media/products/'),
            preserve_default=False,
        ),
    ]
